### ISSUE TITLE
New URL parameters no longer working

### ISSUE THREAD

**Issue by dstubbins** [Esri/embed-template#1]
What happened to all the new embedding url options documented here http://blogs.esri.com/esri/arcgis/2015/02/19/new-options-for-embedding-maps/

In particular the "find=xxxxxx"  this was hugely useful and we just rolled out lots of sites that integrate with backoffice systems using the webmap feature service search option, and passing in a field value such as an identifier using the find parameter to display a map of a specific asset..

As far as I can see that option is no longer in the code or in ArcGIS online and there are no other templates that support this.

**Comment by kellyhutchins** [comment]
@dstubbins looks like a bug -we'll fix it for the next release. In the meantime you can add a marker at a certain location using logic like this: 
http://jsapi.maps.arcgis.com/apps/Embed/index.html?webmap=bf7cf1b96d4f4315bb1a4bb35f162fc4&marker=-122.332;47.606;;;;

**Comment by kellyhutchins** [comment]
Update code for this repo to include the fix will be updated in Online at the next release.

**Comment by dstubbins** [comment]
Thx for fixing this so quickly!
