### ISSUE TITLE
Search Does not work against layers from ArcGIS Server version < 10.3

### ISSUE THREAD

**Issue by dstubbins** [Esri/embed-template#2]
The search tool does not seem to work against feature layers in any ArcGIS server versions other than 10.3.  even at 10.3 it only works against services with SupportsPagination = true which depends on the underlying database.

Throws:
Error: Pagination is not supported.

This may be a problem with the underlying search widget, as the ArcGIS Online viewer also errors like this now.  It would be good if you could still search even with more limited functionality.

**Comment by kellyhutchins** [comment]
@dstubbins  looks like it is an issue with the search widget. I have updated the template source here on github with a workaround that should fix this issue until the next version of the JSAPI is released.
