### ISSUE TITLE
Search does not Search correct attribute field

### ISSUE THREAD

**Issue by esridoyle** [Esri/embed-template#3]
The Search in Feature Layer does not search the attribute field specified in the webmap.

**Comment by MKellyEsri** [comment]
main.js line 274 needs to be changed from

source.searchField = [searchLayer.field.name];

to

source.searchFields = [searchLayer.field.name];

**Comment by kellyhutchins** [comment]
@MKellyEsri  is correct. Its fixed in the source now.
