### ISSUE TITLE
Enhancement: add parameter in the configuration to hide "Edited by.."

### ISSUE THREAD

**Issue by jguard-zz** [Esri/embed-template#9]
Hello,
I received some customer feedback on the minimalist application template to have the option to remove the Edited by display in the Info window (from the pop-up). The customer does not have the ability to download and re-host a custom copy of this application and they would prefer to have a parameter button to hide this display in the hosted version.
See image below for reference.
Thanks!
Julia
![minimalistenhancement](https://user-images.githubusercontent.com/7528583/38397144-6d41ca4e-38e8-11e8-94e0-905b572b8ecd.png)

**Comment by jguard-zz** [comment]
I'm back! Solved this issue. It is tied to the new setting for hosted feature services called "keep track of who created and last updated features". This is turned on and greyed out by default. So you have to check ON editing, uncheck this setting and check OFF editing > Save to make this change. This was then reflected in the minimalist template application. Thanks.
![keeptrack](https://user-images.githubusercontent.com/7528583/38397604-15bda1a0-38eb-11e8-82b4-238c902bb7af.png)

**Comment by kellyhutchins** [comment]
Thanks for the update.
